spring.application.name=processamento-pagamentos

spring.datasource.url=jdbc:postgresql://localhost:5433/processamento_pagamentos

spring.datasource.username=postgres

spring.datasource.password=jeteryan

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true